name: Arch Linux CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu runner as the host
    container:
      image: archlinux:base-devel  # Arch Linux container

    steps:
    - name: Update System and Install Dependencies
      run: |
        pacman -Syu --noconfirm  # Sync package databases and update
        pacman -S --noconfirm git  # Install git (required for actions/checkout)

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Run Scripts
      run: |
        echo "Hello from Arch Linux!"
        echo "Add your build/test/deploy commands here"
